#!/bin/sh
set -e

: "${KIT_API_LOGIN:?Нужен KIT_API_LOGIN}"
: "${KIT_API_PASSWORD:?Нужен KIT_API_PASSWORD}"
: "${KIT_API_COMPANY_ID:?Нужен KIT_API_COMPANY_ID}"
: "${YOUGILE_API_KEY:?Нужен YOUGILE_API_KEY}"
: "${YOUGILE_CHAT_ID:?Нужен YOUGILE_CHAT_ID}"
: "${TELEGRAM_BOT_TOKEN:?Нужен TELEGRAM_BOT_TOKEN}"
: "${TELEGRAM_CHAT_ID:?Нужен TELEGRAM_CHAT_ID}"
: "${DAYS_FOR_AVERAGE:?Нужен DAYS_FOR_AVERAGE}"
: "${SALES_DROP_PERCENT:?Нужен SALES_DROP_PERCENT}"

LOG_DIR="/var/log/sale_monitoring_bot"
mkdir -p "$LOG_DIR"
touch "$LOG_DIR/cron.log"

python <<'PY'
import os
import shlex
import stat

keys = (
    "KIT_API_LOGIN",
    "KIT_API_PASSWORD",
    "KIT_API_COMPANY_ID",
    "YOUGILE_API_KEY",
    "YOUGILE_CHAT_ID",
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_CHAT_ID",
    "YOUGILE_BASE_URL",
    "DAYS_FOR_AVERAGE",
    "SALES_DROP_PERCENT",
    "TZ",
    "LAST_SALE_LOOKUP_DAYS",
)
lines = ["# generated by entrypoint"]
for key in keys:
    value = os.environ.get(key, "")
    lines.append(f"export {key}={shlex.quote(value)}")
content = "\n".join(lines) + "\n"
path = "/app/cron_env.sh"
with open(path, "w", encoding="utf-8") as f:
    f.write(content)
os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
PY

cron_tz="${TZ:-Asia/Yekaterinburg}"
cron_file="/etc/cron.d/sale_monitoring_bot"

{
  printf '%s\n' "SHELL=/bin/sh"
  printf '%s\n' "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  printf '%s\n' "HOME=/root"
  printf '%s\n' "TZ=$cron_tz"
  printf '%s\n' "0 8 * * * root /bin/sh /app/run_cron_report.sh >> $LOG_DIR/cron.log 2>&1"
  printf '%s\n' "0 15 * * * root /bin/sh /app/run_cron_report.sh --no-sales-today >> $LOG_DIR/cron.log 2>&1"
  printf '%s\n' ""
} > "$cron_file"

chmod 0644 "$cron_file"

cron -f
